### ISSUE TITLE
Call from another container

### ISSUE THREAD

**Issue by ckpm** [MTG/essentia-docker#6]

**Comment by alastair** [comment]
One common way of doing this is to mount the docker control socket from your host into your container, so that running docker inside that container will control docker on the host: https://medium.com/better-programming/about-var-run-docker-sock-3bfd276e12fd

Note that this can be a significant security issue if you run non-trusted containers as it would allow a container full access over all of your docker containers.

alternatively, you could base your other container off this one (e.g. `FROM mtgupf/essentia`), so that both the essentia extractors and your code are in the same container.

Another option that we could support in the future is to have an image with statically compiled versions of the extractors so that you can copy the one that you want into your container.
